// <auto-generated />
using System;
using Example.Entities.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Example.Entities.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    partial class ExampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Example.Entities.Models.Process", b =>
                {
                    b.Property<Guid>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Oid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeqNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SortNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StampCreate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StampEdit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StampSync")
                        .HasColumnType("TEXT");

                    b.HasKey("UId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("Example.Entities.Models.TimeSheet", b =>
                {
                    b.Property<Guid>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Oid")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProcessUId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeqNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SortNum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StampCreate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StampEdit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StampSync")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("UId");

                    b.HasIndex("ProcessUId");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("Example.Entities.Models.TimeSheet", b =>
                {
                    b.HasOne("Example.Entities.Models.Process", "Process")
                        .WithMany("TimeSheets")
                        .HasForeignKey("ProcessUId");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("Example.Entities.Models.Process", b =>
                {
                    b.Navigation("TimeSheets");
                });
#pragma warning restore 612, 618
        }
    }
}
